### ISSUE TITLE
Protection of unprotectable items.

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#61]
Deadbolt-2.1.2.jar
This server is running CraftBukkit version git-Bukkit-1.2.3-R0.2-53-g1fa045d-b2092jnks (MC: 1.2.3) (Implementing API version 1.2.3-R0.3-SNAPSHOT)

```
members:
  permissions:
    deadbolt.user.create.door: false
    deadbolt.user.create.trapdoor: false
    deadbolt.user.create.fencegate: false
  worlds:
    worldcreative:
      permissions.build: true
      deadbolt.user.color: false
      deadbolt.user.create.chest: true
      deadbolt.user.create.dispenser: true
      deadbolt.user.create.furnace: true
      deadbolt.user.create.brewery: true
      deadbolt.user.create.enchant: true
      deadbolt.user.create.cauldron: true
```

Place a dispenser/furnace, then place a fence gate next to it. Fence gate is protected (shouldn't be).
